// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAICzrE8OBNROfERwVJ3KxX_An12RtfHe4',
    appId: '1:1013301469144:web:1bc7237e70d8e8a9965cad',
    messagingSenderId: '1013301469144',
    projectId: 'signin-e1',
    authDomain: 'signin-e1.firebaseapp.com',
    storageBucket: 'signin-e1.appspot.com',
    measurementId: 'G-1QWPBTECK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrQFxyMje8cbCmlhR1Rae0ufAFpmiRF-A',
    appId: '1:1013301469144:android:3f32cc848a3780a3965cad',
    messagingSenderId: '1013301469144',
    projectId: 'signin-e1',
    storageBucket: 'signin-e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQu3tYQRuQtIbFnN27tx0lRbmqEDytnA',
    appId: '1:1013301469144:ios:4f0dd2c144d299cb965cad',
    messagingSenderId: '1013301469144',
    projectId: 'signin-e1',
    storageBucket: 'signin-e1.appspot.com',
    iosClientId: '1013301469144-fuvbmi8bh6up2iqjhm4efd8fn4borodc.apps.googleusercontent.com',
    iosBundleId: 'com.example.vize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuQu3tYQRuQtIbFnN27tx0lRbmqEDytnA',
    appId: '1:1013301469144:ios:4f0dd2c144d299cb965cad',
    messagingSenderId: '1013301469144',
    projectId: 'signin-e1',
    storageBucket: 'signin-e1.appspot.com',
    iosClientId: '1013301469144-fuvbmi8bh6up2iqjhm4efd8fn4borodc.apps.googleusercontent.com',
    iosBundleId: 'com.example.vize',
  );
}
